/**
 * Vercel Edge Middleware for Markdown content negotiation.
 *
 * Copy this file to the ROOT of your Astro project (next to
 * astro.config.mjs).  Vercel picks it up automatically — no extra
 * config needed.
 *
 * When a request's Accept header includes `text/markdown`, the
 * middleware rewrites the URL to the `.md` sibling generated by
 * astro-md-content-negotiation.
 *
 * Pair with the following in your vercel.json to set the MIME type:
 *
 *   {
 *     "headers": [
 *       {
 *         "source": "/(.*)\\.md",
 *         "headers": [
 *           { "key": "Content-Type", "value": "text/markdown; charset=utf-8" },
 *           { "key": "Vary", "value": "Accept" }
 *         ]
 *       }
 *     ]
 *   }
 */

import { next, rewrite } from "@vercel/edge";

export default function middleware(request: Request) {
  const accept = request.headers.get("accept") || "";

  if (!accept.includes("text/markdown")) {
    return next();
  }

  const url = new URL(request.url);
  const { pathname } = url;

  // Skip static assets, API routes, and Vercel internals.
  if (
    pathname.startsWith("/_") ||
    pathname.startsWith("/api/") ||
    pathname.includes(".")
  ) {
    return next();
  }

  // Rewrite to the .md file produced by the build.
  const mdPath = pathname.endsWith("/")
    ? `${pathname}index.md`
    : `${pathname}/index.md`;

  url.pathname = mdPath;

  return next({
    request: { url: url.toString() },
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      Vary: "Accept",
    },
  });
}

export const config = {
  matcher: ["/((?!_next|_vercel|api|.*\\..*).*)"],
};
